export const ROUTES = {
  home: "/",
  offers: "/offers",
  favourites: "/favourites",
  bookings: "/bookings",
  bookingResult: "/bookings/result",
  profile: "/profile",
  profileEdit: "/profile/edit",
  wallet: "/wallet",
  /** @deprecated Use wallet */
  alterCash: "/wallet",
  membership: "/membership",
  membershipResult: "/membership/result",
  about: "/about",
  terms: "/terms",
  blog: "/blog",
  privacy: "/privacy",
  contact: "/contact",
  careers: "/careers",
  help: {
    root: "/help",
    faq: "/help/faq",
    contact: "/help/contact",
    support: "/help/support",
  },
  auth: {
    login: "/login",
    register: "/register",
    password: "/login/password",
    admin: "/auth/admin",
  },
  search: "/search",
  cities: "/cities",
  propertyDetail: (slug: string) => `/properties/${slug}`,
  checkout: (slug: string) => `/properties/${slug}/checkout`,
  checkoutLogin: (slug: string) => `/properties/${slug}/checkout/login`,
  /** @deprecated redirects to checkout */
  bookingSummary: (slug: string) => `/properties/${slug}/book`,
  /** @deprecated redirects to checkout login */
  bookingLogin: (slug: string) => `/properties/${slug}/book/login`,
  admin: {
    root: "/admin",
    properties: "/admin/properties",
    bookings: "/admin/bookings",
    booking: (id: string) => `/admin/bookings/${id}`,
    users: "/admin/users",
    settings: "/admin/settings",
    cities: "/admin/cities",
  },
} as const;
