import type { LucideIcon } from "lucide-react";
import {
  AirVentIcon,
  ConciergeBellIcon,
  DumbbellIcon,
  ParkingCircleIcon,
  SparklesIcon,
  UtensilsCrossedIcon,
  WavesIcon,
  WifiIcon,
  BathIcon,
  BedDoubleIcon,
  CarIcon,
  CoffeeIcon,
  DoorOpenIcon,
  FanIcon,
  HeaterIcon,
  KeyRoundIcon,
  PawPrintIcon,
  ShieldCheckIcon,
  ShirtIcon,
  ShowerHeadIcon,
  TvIcon,
  WineIcon,
  AccessibilityIcon,
  BabyIcon,
  BriefcaseIcon,
  CigaretteOffIcon,
  ClockIcon,
  FerrisWheelIcon,
  FlameIcon,
  Flower2Icon,
  Gamepad2Icon,
  LampIcon,
  RefrigeratorIcon,
  SofaIcon,
  TreesIcon,
  UmbrellaIcon,
  WashingMachineIcon,
} from "lucide-react";

const AMENITY_ICONS: Array<{ match: RegExp; icon: LucideIcon }> = [
  { match: /wifi|wi-fi|internet/, icon: WifiIcon },
  { match: /pool|swim/, icon: WavesIcon },
  { match: /park/, icon: ParkingCircleIcon },
  { match: /gym|fitness|workout/, icon: DumbbellIcon },
  { match: /air.?cond|ac\b|cooling/, icon: AirVentIcon },
  { match: /restaurant|dining|food/, icon: UtensilsCrossedIcon },
  { match: /room service|concierge|front desk|reception/, icon: ConciergeBellIcon },
  { match: /breakfast|coffee/, icon: CoffeeIcon },
  { match: /tv|television/, icon: TvIcon },
  { match: /bath|tub/, icon: BathIcon },
  { match: /shower/, icon: ShowerHeadIcon },
  { match: /laundry|washer/, icon: WashingMachineIcon },
  { match: /pet/, icon: PawPrintIcon },
  { match: /bar|wine|lounge/, icon: WineIcon },
  { match: /spa|massage|wellness/, icon: Flower2Icon },
  { match: /heat/, icon: HeaterIcon },
  { match: /fan/, icon: FanIcon },
  { match: /bed|king|queen/, icon: BedDoubleIcon },
  { match: /car|taxi|transfer/, icon: CarIcon },
  { match: /safe|security/, icon: ShieldCheckIcon },
  { match: /key|access/, icon: KeyRoundIcon },
  { match: /iron|laundry press/, icon: ShirtIcon },
  { match: /elevator|lift|door/, icon: DoorOpenIcon },
  { match: /wheelchair|accessib/, icon: AccessibilityIcon },
  { match: /baby|crib|kid/, icon: BabyIcon },
  { match: /business|meeting|desk/, icon: BriefcaseIcon },
  { match: /smoke|non.?smok/, icon: CigaretteOffIcon },
  { match: /24|round.?the.?clock/, icon: ClockIcon },
  { match: /garden|tree/, icon: TreesIcon },
  { match: /beach|umbrella/, icon: UmbrellaIcon },
  { match: /game|play/, icon: Gamepad2Icon },
  { match: /fridge|minibar|refriger/, icon: RefrigeratorIcon },
  { match: /sofa|living/, icon: SofaIcon },
  { match: /lamp|light/, icon: LampIcon },
  { match: /fire|bonfire/, icon: FlameIcon },
  { match: /amusement|ferris/, icon: FerrisWheelIcon },
];

export function amenityIcon(name: string, stored?: string | null): LucideIcon {
  if (stored) {
    const fromStore = AMENITY_ICONS.find((entry) =>
      entry.match.test(stored.toLowerCase()),
    );
    if (fromStore) return fromStore.icon;
  }
  const lower = name.toLowerCase();
  return AMENITY_ICONS.find((entry) => entry.match.test(lower))?.icon ?? SparklesIcon;
}
